// <auto-generated />
using System;
using LexManagerProMax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LexManagerProMax.Infrastructure.Migrations
{
    [DbContext(typeof(LexManagerProMaxDbContext))]
    partial class LexManagerProMaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.AI.MessaggioAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessioneAIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessioneAIId");

                    b.ToTable("MessaggiAI");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.AI.SessioneAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSessione")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FascicoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TipoRicerca")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SessioniAI");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.Fascicolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Giudice")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrRG")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rito")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("Tribunale")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Fascicoli");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.FascicoloSoggetto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FascicoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SoggettoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FascicoloId");

                    b.HasIndex("SoggettoId");

                    b.ToTable("FascicoloSoggetti");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.Soggetto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CellulareUno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataNascita")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FormaGiuridica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCliente")
                        .HasColumnType("bit");

                    b.Property<bool>("IsControparte")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LuogoNascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Pec")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RagioneSociale")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Via")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique()
                        .HasFilter("[CodiceFiscale] IS NOT NULL");

                    b.HasIndex("PartitaIva")
                        .IsUnique()
                        .HasFilter("[PartitaIva] IS NOT NULL");

                    b.HasIndex("Cognome", "Nome");

                    b.ToTable("Soggetti");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Atti.ModelloAtto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersioneCorrente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ModelliAtti");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Atti.VersioneModello", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModelloAttoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Versione")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelloAttoId");

                    b.ToTable("VersioniModello");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.AI.MessaggioAI", b =>
                {
                    b.HasOne("LexManagerProMax.Domain.Entities.AI.SessioneAI", null)
                        .WithMany("Messaggi")
                        .HasForeignKey("SessioneAIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.Fascicolo", b =>
                {
                    b.HasOne("LexManagerProMax.Domain.Entities.Anagrafica.Soggetto", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.FascicoloSoggetto", b =>
                {
                    b.HasOne("LexManagerProMax.Domain.Entities.Anagrafica.Fascicolo", "Fascicolo")
                        .WithMany("Controparti")
                        .HasForeignKey("FascicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexManagerProMax.Domain.Entities.Anagrafica.Soggetto", "Soggetto")
                        .WithMany()
                        .HasForeignKey("SoggettoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fascicolo");

                    b.Navigation("Soggetto");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Atti.VersioneModello", b =>
                {
                    b.HasOne("LexManagerProMax.Domain.Entities.Atti.ModelloAtto", null)
                        .WithMany("Versioni")
                        .HasForeignKey("ModelloAttoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.AI.SessioneAI", b =>
                {
                    b.Navigation("Messaggi");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Anagrafica.Fascicolo", b =>
                {
                    b.Navigation("Controparti");
                });

            modelBuilder.Entity("LexManagerProMax.Domain.Entities.Atti.ModelloAtto", b =>
                {
                    b.Navigation("Versioni");
                });
#pragma warning restore 612, 618
        }
    }
}
